# -*- coding: utf-8 -*-
"""Cópia de Projeto_Final_Impacta.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pYRd_i09ZXZPcfBllhowpzyOxoMkdoWr
"""

import pandas as pd
import requests

url = "https://dadosabertos.camara.leg.br/api/v2/deputados?ordem=ASC&ordenarPor=nome"
resultado = requests.get(url)

deputados = pd.DataFrame(resultado.json()['dados'])

gastos = []

for id in deputados.id:
  url_despesa = 'https://dadosabertos.camara.leg.br/api/v2/deputados/'+str(id)+'/despesas?ordem=ASC&ano=2023'
  resposta = requests.get(url_despesa)
  gasto = pd.DataFrame(resposta.json()['dados'])
  gasto['id'] = id
  gastos.append(gasto)

len(gastos)

total = pd.concat(gastos)

total.isnull().sum()

del total['urlDocumento']

del total['dataDocumento']

total.head()

total.shape

total.numRessarcimento.value_counts()

del total['numRessarcimento']

print(total.shape)
total.drop_duplicates()
print(total.shape)

total.info()

total.describe()

total.nomeFornecedor.value_counts()

total.nomeFornecedor = [str(fornecedor).upper().replace("S.A.", 'S.A').replace('S/A', 'S.A') for fornecedor in total.nomeFornecedor]

total.nomeFornecedor.value_counts()

from sqlalchemy import create_engine

engine = create_engine('sqlite:///dados.abertos.db')

deputados.to_sql('deputados', engine)

total.to_sql('despesas_total', engine)

#Análise

total.head()

deputados.head()

total = total.merge(deputados, on=['id'])

total.head()

gastos_deputados = total.groupby(['nome', 'siglaPartido']).sum()[['valorDocumento', 'valorLiquido']]

gastos_deputados = gastos_deputados.sort_values('valorDocumento', ascending=False)

gastos_deputados.head(10)

gastos_deputados.tail(10)

print(total)

finalDF = total.to_excel('finaldata.xlsx')